### ISSUE TITLE
Change buttons on Trash view

### ISSUE THREAD

**Issue by JEstes93** [cooksystemsinc/final-project-orange#114]
Change the "Create Folder" and "Upload" buttons to "Restore All Items" and "Delete All Items" buttons when in the Trash view.
### Features
- [x] Both options connected via Redux
- [x] Options prompt for verification ("Are you sure?")
- [x] Options apply recursively for folders
### Tasks
- [x] Create verification modal
- [x] Connect via Redux

**Comment by JEstes93** [comment]
Going to implement the verification ("Are you sure?") stage via modal.

**Comment by JEstes93** [comment]
Verification modal created

**Comment by JEstes93** [comment]
Completed, but left DeleteAll functionality disabled for DB seed safety
