### ISSUE TITLE
Separate Redux Epic/Issues into more specific pieces

### ISSUE THREAD

**Issue by JEstes93** [cooksystemsinc/final-project-orange#49]
I'd like to propose to the team that we divide the current Redux Epic/Issues.

A new Epic and Issues should be created specifically for the implementation of each duck, while the current existing ones will be resolved simply for creation/initialization of the base files/skeleton.

Preferably the new Issues would utilize checklists to track file-specific completion of features and additions.

Pending confirmation with team, I'll handle this process. Here's a proposition for the structure of these additions:

### Epic
- [ ] Implement Redux ducks

### Issues
- [ ] Implement index.duck.js
- [ ] Implement library.duck.js
- [ ] Implement ui-state.duck.js
- [ ] Implement trash.duck.js

Checklists/sub-issues to be formulated during creation of these issues.
